<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="QLDH1.aspx.cs" Inherits="QLDH" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="nen">
    <asp:Label ID="Label2" runat="server" Text="QUẢN LÝ ĐƠN HÀNG"></asp:Label>
        <br />
        <br />
        <asp:Panel ID="Panel1" runat="server">
            Ngày bắt đầu:
            <asp:TextBox ID="txt_ngaybd" runat="server" TextMode="Date"></asp:TextBox>
            <asp:CompareValidator ID="CompareValidator1" runat="server" ControlToCompare="txt_ngaybd" ControlToValidate="txt_ngaykt" ErrorMessage="Ngày bắt đầu phải trước ngày kết thúc" ForeColor="Red" Operator="GreaterThan" Type="Date">(*)</asp:CompareValidator>
            <br />
            <br />
            Ngày kết thúc:
            <asp:TextBox ID="txt_ngaykt" runat="server" TextMode="Date"></asp:TextBox>
            &nbsp;<br />
            <br />
            <asp:Button ID="btn_loc" runat="server" OnClick="btn_loc_Click" Text="Lọc" UseSubmitBehavior="False" />
           
            <br />
            <asp:ValidationSummary ID="ValidationSummary1" runat="server" ShowMessageBox="True" ShowSummary="False" />
        </asp:Panel>
       
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="MaHD,MaSP" DataSourceID="qldh1" GridLines="Vertical">
            <AlternatingRowStyle BackColor="Gainsboro" />
            <Columns>
                <asp:BoundField DataField="MaHD" HeaderText="MaHD" ReadOnly="True" SortExpression="MaHD" />
                <asp:BoundField DataField="MaSP" HeaderText="MaSP" ReadOnly="True" SortExpression="MaSP" />
                <asp:BoundField DataField="SoLuong" HeaderText="SoLuong" SortExpression="SoLuong" />
                <asp:BoundField DataField="DonGia" HeaderText="DonGia" SortExpression="DonGia" />
                <asp:BoundField DataField="ThanhTien" HeaderText="ThanhTien" SortExpression="ThanhTien" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />
        </asp:GridView>
        <asp:SqlDataSource ID="qldh1" runat="server" ConnectionString="<%$ ConnectionStrings:WebThietBiMayTinhConnectionString %>" SelectCommand="SELECT * FROM [CHITIETHOADON]"></asp:SqlDataSource>
       
        <br />
    <br />
    
    <br />
        <%-- <asp:SqlDataSource ID="ds_hoadon" runat="server"
        ConnectionString="<%$ ConnectionStrings:dotnet1 %>"
        SelectCommand="Select *,'~/ChiTietHoaDon.aspx?md='+cast(MaHD as char) as ct from HOADON">

    </asp:SqlDataSource>--%>
        <asp:Button ID="btn_Xoa" runat="server" OnClick="btn_Xoa_Click" Text="Xóa" UseSubmitBehavior="False" />
        <asp:Button ID="btn_chitiet" runat="server" OnClick="btn_chitiet_Click" Text="Chi tiết" UseSubmitBehavior="False" />
        <br />
        <br />
        <br />
    </div>
</asp:Content>

